#ifndef _PARAM__H__
#define _PARAM__H__


/* Module MULTI_INPUT_0 Location Start - Non Modulo Location Start*/
#define MULTI_INPUT_0_COUNT    0

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/


/* Module FILTER_GRAPHICAL_EQ_0 Location Start - Non Modulo Location Start*/
#define FILTER_GRAPHICAL_EQ_0_COUNT    26

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define FILTER_GRAPHICAL_EQ_0_NUMFILTER_ADDR  32768
#define FILTER_GRAPHICAL_EQ_0_NUMFILTER_VALUE  5
#define FILTER_GRAPHICAL_EQ_0_FC_0_ADDR  32769
#define FILTER_GRAPHICAL_EQ_0_FC_0_VALUE  62.5
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_0_ADDR  32770
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_0_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_0_Q_0_ADDR  32771
#define FILTER_GRAPHICAL_EQ_0_Q_0_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_0_TYPE_0_ADDR  32772
#define FILTER_GRAPHICAL_EQ_0_TYPE_0_VALUE  0
#define FILTER_GRAPHICAL_EQ_0_BYPASS_0_ADDR  32773
#define FILTER_GRAPHICAL_EQ_0_BYPASS_0_VALUE  2
#define FILTER_GRAPHICAL_EQ_0_FC_1_ADDR  32774
#define FILTER_GRAPHICAL_EQ_0_FC_1_VALUE  125.0
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_1_ADDR  32775
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_1_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_0_Q_1_ADDR  32776
#define FILTER_GRAPHICAL_EQ_0_Q_1_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_0_TYPE_1_ADDR  32777
#define FILTER_GRAPHICAL_EQ_0_TYPE_1_VALUE  0
#define FILTER_GRAPHICAL_EQ_0_BYPASS_1_ADDR  32778
#define FILTER_GRAPHICAL_EQ_0_BYPASS_1_VALUE  2
#define FILTER_GRAPHICAL_EQ_0_FC_2_ADDR  32779
#define FILTER_GRAPHICAL_EQ_0_FC_2_VALUE  250.0
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_2_ADDR  32780
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_2_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_0_Q_2_ADDR  32781
#define FILTER_GRAPHICAL_EQ_0_Q_2_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_0_TYPE_2_ADDR  32782
#define FILTER_GRAPHICAL_EQ_0_TYPE_2_VALUE  0
#define FILTER_GRAPHICAL_EQ_0_BYPASS_2_ADDR  32783
#define FILTER_GRAPHICAL_EQ_0_BYPASS_2_VALUE  2
#define FILTER_GRAPHICAL_EQ_0_FC_3_ADDR  32784
#define FILTER_GRAPHICAL_EQ_0_FC_3_VALUE  500.0
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_3_ADDR  32785
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_3_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_0_Q_3_ADDR  32786
#define FILTER_GRAPHICAL_EQ_0_Q_3_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_0_TYPE_3_ADDR  32787
#define FILTER_GRAPHICAL_EQ_0_TYPE_3_VALUE  0
#define FILTER_GRAPHICAL_EQ_0_BYPASS_3_ADDR  32788
#define FILTER_GRAPHICAL_EQ_0_BYPASS_3_VALUE  2
#define FILTER_GRAPHICAL_EQ_0_FC_4_ADDR  32789
#define FILTER_GRAPHICAL_EQ_0_FC_4_VALUE  1000.0
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_4_ADDR  32790
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_4_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_0_Q_4_ADDR  32791
#define FILTER_GRAPHICAL_EQ_0_Q_4_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_0_TYPE_4_ADDR  32792
#define FILTER_GRAPHICAL_EQ_0_TYPE_4_VALUE  0
#define FILTER_GRAPHICAL_EQ_0_BYPASS_4_ADDR  32793
#define FILTER_GRAPHICAL_EQ_0_BYPASS_4_VALUE  2


/* Module FILTER_GRAPHICAL_EQ_1 Location Start - Non Modulo Location Start*/
#define FILTER_GRAPHICAL_EQ_1_COUNT    26

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define FILTER_GRAPHICAL_EQ_1_NUMFILTER_ADDR  65536
#define FILTER_GRAPHICAL_EQ_1_NUMFILTER_VALUE  5
#define FILTER_GRAPHICAL_EQ_1_FC_0_ADDR  65537
#define FILTER_GRAPHICAL_EQ_1_FC_0_VALUE  62.5
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_0_ADDR  65538
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_0_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_1_Q_0_ADDR  65539
#define FILTER_GRAPHICAL_EQ_1_Q_0_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_1_TYPE_0_ADDR  65540
#define FILTER_GRAPHICAL_EQ_1_TYPE_0_VALUE  0
#define FILTER_GRAPHICAL_EQ_1_BYPASS_0_ADDR  65541
#define FILTER_GRAPHICAL_EQ_1_BYPASS_0_VALUE  2
#define FILTER_GRAPHICAL_EQ_1_FC_1_ADDR  65542
#define FILTER_GRAPHICAL_EQ_1_FC_1_VALUE  125.0
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_1_ADDR  65543
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_1_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_1_Q_1_ADDR  65544
#define FILTER_GRAPHICAL_EQ_1_Q_1_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_1_TYPE_1_ADDR  65545
#define FILTER_GRAPHICAL_EQ_1_TYPE_1_VALUE  0
#define FILTER_GRAPHICAL_EQ_1_BYPASS_1_ADDR  65546
#define FILTER_GRAPHICAL_EQ_1_BYPASS_1_VALUE  2
#define FILTER_GRAPHICAL_EQ_1_FC_2_ADDR  65547
#define FILTER_GRAPHICAL_EQ_1_FC_2_VALUE  250.0
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_2_ADDR  65548
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_2_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_1_Q_2_ADDR  65549
#define FILTER_GRAPHICAL_EQ_1_Q_2_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_1_TYPE_2_ADDR  65550
#define FILTER_GRAPHICAL_EQ_1_TYPE_2_VALUE  0
#define FILTER_GRAPHICAL_EQ_1_BYPASS_2_ADDR  65551
#define FILTER_GRAPHICAL_EQ_1_BYPASS_2_VALUE  2
#define FILTER_GRAPHICAL_EQ_1_FC_3_ADDR  65552
#define FILTER_GRAPHICAL_EQ_1_FC_3_VALUE  500.0
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_3_ADDR  65553
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_3_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_1_Q_3_ADDR  65554
#define FILTER_GRAPHICAL_EQ_1_Q_3_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_1_TYPE_3_ADDR  65555
#define FILTER_GRAPHICAL_EQ_1_TYPE_3_VALUE  0
#define FILTER_GRAPHICAL_EQ_1_BYPASS_3_ADDR  65556
#define FILTER_GRAPHICAL_EQ_1_BYPASS_3_VALUE  2
#define FILTER_GRAPHICAL_EQ_1_FC_4_ADDR  65557
#define FILTER_GRAPHICAL_EQ_1_FC_4_VALUE  1000.0
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_4_ADDR  65558
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_4_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_1_Q_4_ADDR  65559
#define FILTER_GRAPHICAL_EQ_1_Q_4_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_1_TYPE_4_ADDR  65560
#define FILTER_GRAPHICAL_EQ_1_TYPE_4_VALUE  0
#define FILTER_GRAPHICAL_EQ_1_BYPASS_4_ADDR  65561
#define FILTER_GRAPHICAL_EQ_1_BYPASS_4_VALUE  2


/* Module MULTI_OUTPUT_0 Location Start - Non Modulo Location Start*/
#define MULTI_OUTPUT_0_COUNT    0

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/




#endif